2021-08-05 22:50:42.421 [main] ERROR com.imooc.o2o.service.impl.WechatAuthServiceImpl - insertWechatAuth error:org.springframework.dao.DuplicateKeyException: 
### Error updating database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'albert' for key 'open_id'
### The error may exist in file [/Users/albert/Documents/GitHub/o2o_springboot/target/classes/mapper/WechatAuthDao.xml]
### The error may involve com.imooc.o2o.dao.WechatAuthDao.insertWechatAuth-Inline
### The error occurred while setting parameters
### SQL: INSERT   INTO   tb_wechat_auth(user_id,open_id,create_time)   VALUES   (?,?,?)
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'albert' for key 'open_id'
; Duplicate entry 'albert' for key 'open_id'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'albert' for key 'open_id'
